services:
  - type: worker
    name: telegram-bot-sateq
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: DATA_DIR
        value: /data
