services:
  - type: web
    name: telegram-bot-sateq
    runtime: node
    region: frankfurt
    plan: free
    buildCommand: npx pnpm@10 install --no-frozen-lockfile
    startCommand: npx pnpm@10 --filter @workspace/telegram-bot run start
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production
